# Generated by Django 4.2.3 on 2023-07-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0002_remove_meetingroom_booking_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingroom',
            old_name='sstart_time',
            new_name='start_time',
        ),
    ]
