# Generated by Django 4.2.3 on 2023-07-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0003_configuration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='user',
        ),
    ]
