# Generated by Django 4.2.3 on 2023-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0006_remove_configuration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
    ]
