# Generated by Django 4.2.3 on 2023-07-18 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0007_alter_meetingroom_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='floor',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
