# Generated by Django 4.2.3 on 2023-07-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0008_alter_meetingroom_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='order',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spiderapp.meetingroom')),
                ('participants', models.ManyToManyField(blank=True, related_name='meeting_rooms', through='spiderapp.MeetingParticipant', to='spiderapp.employee')),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_rooms', to='spiderapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spiderapp.reservation'),
            preserve_default=False,
        ),
    ]
