# Generated by Django 4.2.3 on 2023-07-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0009_remove_meetingparticipant_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='meeting_room',
        ),
    ]
